name: Deploy resume to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1

      - name: Configure AWS credentials from OIDC token
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::801214068283:role/ResumeGithubWriteRole
          aws-region: us-west-1

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy infrastructure
        run: terraform apply -auto-approve

      - name: Deploy website to S3 bucket
        run: |
          aws s3 sync ./website s3://lucas-dall-resume-bucket --sse AES256
          aws s3 website s3://lucas-dall-resume-bucket --index-document index.html --error-document error.html
