name: Deploy resume to AWS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 0.14.7

            - name: Configure AWS credentials from OIDC token
              id: aws-credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                role-to-assume: arn:aws:iam::801214068283:role/LucasDallResumeGithubRole
                aws-region: us-west-1

            - name: Initialize Terraform
              run: terraform init

            - name: Validate Terraform configuration
              run: terraform validate

            - name: Deploy infrastructure
              run: terraform apply -auto-approve

            - name: Deploy website to S3 bucket
              run: |
                aws s3 sync ./website s3://lucas-dall-resume-bucket --delete
                aws s3 website s3://lucas-dall-resume-bucket --index-document index.html --error-document error.html
