name: Deploy resume to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1

      - name: Configure AWS credentials from OIDC token
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::801214068283:role/ResumeGithubWriteRole
          aws-region: us-west-1

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy infrastructure
        id: apply
        run: terraform apply -auto-approve
      
      - name: Get outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs

      - name: Deploy website to S3 bucket
        run: |
          aws s3 sync ./website s3://${{ steps.tf-outputs.outputs.bucket_name }} --sse AES256
          aws s3 website s3://${{ steps.tf-outputs.outputs.bucket_name }} --index-document index.html --error-document error.html

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ steps.tf-outputs.outputs.distribution_id }} --paths "/*"